//
//  RealAcupointData.swift
//  MAIC
//
//  資料來源：bankroz/acupoint-platform + WHO標準
//  bodyPoint: x=0左→1右, y=0頭頂→1腳底
//

import Foundation

enum RealAcupointData {
    static let all: [Acupoint] = seed()
    static var count: Int { all.count }
    static func byID(_ id: String) -> Acupoint? { all.first { $0.id == id } }
    static func byMeridian(_ meridian: String) -> [Acupoint] { all.filter { $0.meridian == meridian } }

    private static func seed() -> [Acupoint] { [

        .init(id: "LI11", nameZh: "曲池", pinyin: "QuChi",
               meridian: "手阳明大肠经", location: "肘横纹外侧端，屈肘时肘横纹尽头",
               indications: ["发热", "高血压", "手臂疼痛", "风疹"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.84, y: 0.32)),
        .init(id: "LI10", nameZh: "手三里", pinyin: "ShouSanLi",
               meridian: "手阳明大肠经", location: "阳溪与曲池连线上，肘横纹下2寸",
               indications: ["手臂疼痛", "腹痛", "腹泻"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.847, y: 0.347)),
        .init(id: "LI4", nameZh: "合谷", pinyin: "HeGu",
               meridian: "手阳明大肠经", location: "第1、2掌骨之间，约第2掌骨中点桡侧",
               indications: ["头痛", "牙痛", "面瘫", "感冒", "腹痛"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.889, y: 0.483)),
        .init(id: "LU5", nameZh: "尺泽", pinyin: "ChiZe",
               meridian: "手太阴肺经", location: "肘横纹中，肱二头肌腱桡侧",
               indications: ["咳嗽", "哮喘", "咽喉肿痛", "肘臂疼痛"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.16, y: 0.32)),
        .init(id: "LU7", nameZh: "列缺", pinyin: "LieQue",
               meridian: "手太阴肺经", location: "桡骨茎突上方，腕横纹上1.5寸",
               indications: ["咳嗽", "头痛", "颈项强痛", "面瘫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.155, y: 0.341)),
        .init(id: "LU9", nameZh: "太渊", pinyin: "TaiYuan",
               meridian: "手太阴肺经", location: "腕掌侧横纹桡侧，桡动脉搏动处",
               indications: ["咳嗽", "气喘", "腕臂痛", "无脉症"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.123, y: 0.467)),
        .init(id: "PC6", nameZh: "内关", pinyin: "NeiGuan",
               meridian: "手厥阴心包经", location: "腕横纹上2寸，掌长肌腱与桡侧腕屈肌腱之间",
               indications: ["心悸", "失眠", "胃痛", "呕吐", "胸闷"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.847, y: 0.347)),
        .init(id: "HT7", nameZh: "神门", pinyin: "ShenMen",
               meridian: "手少阴心经", location: "腕掌侧横纹尺侧端，尺侧腕屈肌腱桡侧",
               indications: ["失眠", "心悸", "心烦", "健忘"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.84, y: 0.32)),
        .init(id: "TE5", nameZh: "外关", pinyin: "WaiGuan",
               meridian: "手少阳三焦经", location: "腕背横纹上2寸，尺骨与桡骨之间",
               indications: ["发热", "头痛", "耳鸣", "胁痛"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.847, y: 0.347)),
        .init(id: "GB34", nameZh: "阳陵泉", pinyin: "YangLingQuan",
               meridian: "足少阳胆经", location: "腓骨小头前下方凹陷中，八会穴之筋会",
               indications: ["胁痛", "黄疸", "下肢痿痹", "膝痛"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.64, y: 0.64)),
        .init(id: "ST36", nameZh: "足三里", pinyin: "ZuSanLi",
               meridian: "足阳明胃经", location: "犊鼻下3寸，胫骨前嵴外一横指",
               indications: ["胃痛", "腹泻", "下肢痿痹", "保健强壮", "虚劳"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.633, y: 0.683)),
        .init(id: "ST40", nameZh: "丰隆", pinyin: "FengLong",
               meridian: "足阳明胃经", location: "外踝尖上8寸，条口外一横指，胃经络穴",
               indications: ["咳嗽痰多", "头痛", "眩晕", "下肢痿痹"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.649, y: 0.755)),
        .init(id: "SP6", nameZh: "三阴交", pinyin: "SanYinJiao",
               meridian: "足太阴脾经", location: "内踝尖上3寸，胫骨内侧缘后方",
               indications: ["月经不调", "失眠", "腹胀", "下肢痿痹", "遗精"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.633, y: 0.683)),
        .init(id: "SP9", nameZh: "阴陵泉", pinyin: "YinLingQuan",
               meridian: "足太阴脾经", location: "胫骨内侧髁后下方凹陷中",
               indications: ["水肿", "腹胀", "腹泻", "膝痛"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.36, y: 0.64)),
        .init(id: "KI3", nameZh: "太溪", pinyin: "TaiXi",
               meridian: "足少阴肾经", location: "内踝尖与跟腱之间的凹陷中，肾经原穴",
               indications: ["耳鸣", "失眠", "腰痛", "遗精", "月经不调"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.6, y: 0.87)),
        .init(id: "BL40", nameZh: "委中", pinyin: "WeiZhong",
               meridian: "足太阳膀胱经", location: "腘横纹中点，股二头肌腱与半腱肌腱之间",
               indications: ["腰痛", "下肢痿痹", "腹痛", "小便不利"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.64, y: 0.64)),
        .init(id: "BL60", nameZh: "昆仑", pinyin: "KunLun",
               meridian: "足太阳膀胱经", location: "外踝尖与跟腱之间的凹陷中",
               indications: ["头痛", "腰痛", "踝关节扭伤", "癫痫"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.6, y: 0.87)),
        .init(id: "GB30", nameZh: "环跳", pinyin: "HuanTiao",
               meridian: "足少阳胆经", location: "股骨大转子最凸点与骶管裂孔连线的外1/3与内2/3交点",
               indications: ["腰痛", "坐骨神经痛", "下肢痿痹"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.694, y: 0.488)),
        .init(id: "LV3", nameZh: "太冲", pinyin: "TaiChong",
               meridian: "足厥阴肝经", location: "第1、2跖骨结合部前方凹陷中，肝经原穴",
               indications: ["头痛", "眩晕", "月经不调", "胁痛", "高血压"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.594, y: 0.897)),
        .init(id: "CV22", nameZh: "天突", pinyin: "TianTu",
               meridian: "任脉", location: "胸骨上窝正中，约C7水平",
               indications: ["咳嗽", "哮喘", "咽喉肿痛", "呃逆"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.16)),
        .init(id: "CV17", nameZh: "膻中", pinyin: "DanZhong",
               meridian: "任脉", location: "两乳头连线中点，平第4肋间隙(T4水平)",
               indications: ["胸闷", "心悸", "咳嗽", "哮喘", "产后缺乳"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.22)),
        .init(id: "CV15", nameZh: "鸠尾(前胸)", pinyin: "JiuWei",
               meridian: "任脉", location: "剑突下，脐上7寸(T5水平)，任脉络穴",
               indications: ["心痛", "心悸", "胃痛", "癫痫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.45)),
        .init(id: "CV14", nameZh: "巨阙", pinyin: "JuQue",
               meridian: "任脉", location: "脐上6寸，剑突下2寸",
               indications: ["心悸", "胸痛", "胃痛", "呕吐"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.45)),
        .init(id: "CV12", nameZh: "中脘", pinyin: "ZhongWan",
               meridian: "任脉", location: "脐上4寸，胃经募穴，八会穴之腑会",
               indications: ["胃痛", "腹胀", "呕吐", "泄泻", "消化不良"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.45)),
        .init(id: "CV10", nameZh: "下脘(前胸)", pinyin: "XiaWan",
               meridian: "任脉", location: "脐上2寸(T10水平)",
               indications: ["胃痛", "腹胀", "呕吐", "消化不良"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.45)),
        .init(id: "CV8", nameZh: "神阙", pinyin: "ShenQue",
               meridian: "任脉", location: "脐中(L3-L4水平)",
               indications: ["腹痛", "腹泻", "脱证", "水肿"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.42)),
        .init(id: "CV6", nameZh: "气海", pinyin: "QiHai",
               meridian: "任脉", location: "脐下1.5寸(L2水平)",
               indications: ["虚脱", "腹痛", "遗尿", "月经不调", "阳痿"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.45)),
        .init(id: "CV4", nameZh: "关元", pinyin: "GuanYuan",
               meridian: "任脉", location: "脐下3寸，小肠募穴",
               indications: ["遗尿", "阳痿", "月经不调", "腹痛", "虚劳"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.48)),
        .init(id: "CV3", nameZh: "中极", pinyin: "ZhongJi",
               meridian: "任脉", location: "脐下4寸，膀胱募穴",
               indications: ["遗尿", "小便不利", "阳痿", "月经不调"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.45)),
        .init(id: "GV14", nameZh: "大椎", pinyin: "DaZhui",
               meridian: "督脉", location: "第7颈椎棘突下凹陷中，肩中点正后方",
               indications: ["发热", "感冒", "颈椎病", "免疫力低下"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.16)),
        .init(id: "GV13", nameZh: "陶道", pinyin: "TaoDao",
               meridian: "督脉", location: "第1胸椎棘突下(T1水平)",
               indications: ["发热", "头痛", "疟疾", "癫痫"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.45)),
        .init(id: "GV12", nameZh: "身柱", pinyin: "ShenZhu",
               meridian: "督脉", location: "第3胸椎棘突下(T3水平)",
               indications: ["咳嗽", "哮喘", "脊背强痛", "小儿惊风"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.45)),
        .init(id: "GV11", nameZh: "神道(背面)", pinyin: "ShenDao",
               meridian: "督脉", location: "第5胸椎棘突下(T5水平)，背面",
               indications: ["心悸", "失眠", "神经衰弱", "脊背强痛"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.45)),
        .init(id: "GV9", nameZh: "至阳(背面)", pinyin: "ZhiYang",
               meridian: "督脉", location: "第7胸椎棘突下(T7水平)，肩胛骨下角连线中点",
               indications: ["胸胁胀痛", "黄疸", "背痛", "咳嗽"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.27)),
        .init(id: "GV6", nameZh: "脊中(背面)", pinyin: "JiZhong",
               meridian: "督脉", location: "第11胸椎棘突下(T11水平)，背面",
               indications: ["腹泻", "黄疸", "腰脊强痛"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.45)),
        .init(id: "GV4", nameZh: "命门(背面)", pinyin: "MingMen",
               meridian: "督脉", location: "第2腰椎棘突下(L2水平)，与脐相对",
               indications: ["腰痛", "阳痿", "遗精", "月经不调", "腹泻"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.45)),
        .init(id: "GV3", nameZh: "腰阳关", pinyin: "YaoYangGuan",
               meridian: "督脉", location: "第4腰椎棘突下(L4水平)，髋中点正后方",
               indications: ["腰痛", "下肢痿痹", "月经不调", "遗精"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.45)),
        .init(id: "BL13", nameZh: "肺俞", pinyin: "FeiShu",
               meridian: "足太阳膀胱经", location: "第3胸椎棘突下旁开1.5寸，肺之背俞穴",
               indications: ["咳嗽", "哮喘", "感冒", "肺结核"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.45)),
        .init(id: "BL15", nameZh: "心俞", pinyin: "XinShu",
               meridian: "足太阳膀胱经", location: "第5胸椎棘突下旁开1.5寸，心之背俞穴",
               indications: ["心悸", "失眠", "心痛", "胸闷"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.45)),
        .init(id: "BL17", nameZh: "膈俞", pinyin: "GeShu",
               meridian: "足太阳膀胱经", location: "第7胸椎棘突下旁开1.5寸，八会穴之血会",
               indications: ["胸胁痛", "吐血", "贫血", "潮热"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.27)),
        .init(id: "BL18", nameZh: "肝俞", pinyin: "GanShu",
               meridian: "足太阳膀胱经", location: "第9胸椎棘突下旁开1.5寸，肝之背俞穴",
               indications: ["胁痛", "黄疸", "目赤", "头痛"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.45)),
        .init(id: "BL20", nameZh: "脾俞", pinyin: "PiShu",
               meridian: "足太阳膀胱经", location: "第11胸椎棘突下旁开1.5寸，脾之背俞穴",
               indications: ["腹胀", "泄泻", "呕吐", "水肿"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.45)),
        .init(id: "BL21", nameZh: "胃俞", pinyin: "WeiShu",
               meridian: "足太阳膀胱经", location: "第12胸椎棘突下旁开1.5寸，胃之背俞穴",
               indications: ["胃痛", "呕吐", "腹胀", "消化不良"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.38)),
        .init(id: "BL23", nameZh: "肾俞", pinyin: "ShenShu",
               meridian: "足太阳膀胱经", location: "第2腰椎棘突下旁开1.5寸，肾之背俞穴",
               indications: ["腰痛", "阳痿", "遗精", "耳鸣", "水肿"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.45)),
        .init(id: "BL25", nameZh: "大肠俞", pinyin: "DaChangShu",
               meridian: "足太阳膀胱经", location: "第4腰椎棘突下旁开1.5寸，大肠之背俞穴",
               indications: ["便秘", "腹泻", "腰痛", "下肢痿痹"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.45)),
        .init(id: "ST19", nameZh: "不容", pinyin: "BuRong",
               meridian: "足阳明胃经", location: "脐上6寸旁开2寸（胸腹部胃经穴位）",
               indications: ["胃痛", "呕吐", "腹胀", "食欲不振"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.56, y: 0.48)),
        .init(id: "ST21", nameZh: "梁门", pinyin: "LiangMen",
               meridian: "足阳明胃经", location: "脐上4寸旁开2寸（T7水平）",
               indications: ["胃痛", "呕吐", "食欲不振", "腹胀"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.56, y: 0.48)),
        .init(id: "ST25", nameZh: "天枢", pinyin: "TianShu",
               meridian: "足阳明胃经", location: "脐旁2寸，大肠募穴",
               indications: ["腹痛", "腹泻", "便秘", "月经不调"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.56, y: 0.48)),
        .init(id: "ST29", nameZh: "归来", pinyin: "GuiLai",
               meridian: "足阳明胃经", location: "脐下4寸旁开2寸",
               indications: ["月经不调", "带下", "腹痛", "疝气"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.56, y: 0.48)),
        .init(id: "KI16", nameZh: "肓俞", pinyin: "HuangShu",
               meridian: "足少阴肾经", location: "脐旁0.5寸",
               indications: ["腹痛", "泄泻", "便秘"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.53, y: 0.48)),
        .init(id: "SP15", nameZh: "大横", pinyin: "DaHeng",
               meridian: "足太阴脾经", location: "脐旁4寸",
               indications: ["腹痛", "泄泻", "便秘"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.62, y: 0.48)),
        .init(id: "LV14", nameZh: "期门", pinyin: "QiMen",
               meridian: "足厥阴肝经", location: "乳头直下第6肋间隙(T5-T6水平)，肝之募穴",
               indications: ["胁痛", "黄疸", "月经不调"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.62, y: 0.48)),
        .init(id: "GB21", nameZh: "肩井", pinyin: "JianJing",
               meridian: "足少阳胆经", location: "大椎与肩峰连线的中点",
               indications: ["肩背痛", "落枕", "头痛", "乳腺炎"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.59, y: 0.16)),
        .init(id: "CV17_BL", nameZh: "膻中(左侧)", pinyin: "DanZhong_L",
               meridian: "任脉", location: "(同CV17)",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.22)),
        .init(id: "GV29", nameZh: "印堂", pinyin: "YinTang",
               meridian: "经外奇穴(督脉)", location: "两眉头连线中点(印堂奇穴)",
               indications: ["头痛", "失眠", "鼻塞", "眩晕"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.06)),
        .init(id: "EX_HN5", nameZh: "太阳", pinyin: "TaiYang",
               meridian: "经外奇穴", location: "眉梢与目外眦之间向后约一横指凹陷中(左)",
               indications: ["头痛", "目赤肿痛", "面瘫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "ST2", nameZh: "四白", pinyin: "SiBai",
               meridian: "足阳明胃经", location: "目正视，瞳孔直下，眶下孔凹陷中",
               indications: ["目赤肿痛", "面瘫", "三叉神经痛"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.1)),
        .init(id: "ST4", nameZh: "地仓", pinyin: "DiCang",
               meridian: "足阳明胃经", location: "口角外侧旁开0.4寸(左)",
               indications: ["面瘫", "流涎", "口角歪斜"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "ST7", nameZh: "下关", pinyin: "XiaGuan",
               meridian: "足阳明胃经", location: "颧弓下缘，下颌骨髁状突前方凹陷中",
               indications: ["牙痛", "面瘫", "耳鸣", "下颌关节炎"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "LI20", nameZh: "迎香", pinyin: "YingXiang",
               meridian: "手阳明大肠经", location: "鼻翼外缘中点旁开0.5寸，鼻唇沟中(左)",
               indications: ["鼻塞", "鼻出血", "面瘫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.48, y: 0.09)),
        .init(id: "SI18", nameZh: "颧髎", pinyin: "QuanLiao",
               meridian: "手太阳小肠经", location: "目外眦直下，颧骨下缘凹陷中(左)",
               indications: ["面瘫", "牙痛", "三叉神经痛"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "BL2_L", nameZh: "攒竹(左)", pinyin: "CuanZhu",
               meridian: "足太阳膀胱经", location: "眉头凹陷中，眶上切迹处(左)",
               indications: ["头痛", "目赤肿痛", "眼睑跳动"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "BL1_L", nameZh: "睛明(左)", pinyin: "JingMing",
               meridian: "足太阳膀胱经", location: "目内眦角稍上方凹陷中(左)",
               indications: ["目赤肿痛", "迎风流泪", "近视", "夜盲"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "BL1_R", nameZh: "睛明(右)", pinyin: "JingMing",
               meridian: "足太阳膀胱经", location: "目内眦角稍上方凹陷中(右)",
               indications: ["目赤肿痛", "迎风流泪", "近视", "夜盲"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "EX_HN4_L", nameZh: "鱼腰(左)", pinyin: "YuYao",
               meridian: "经外奇穴", location: "瞳孔直上，眉毛中点处(左)",
               indications: ["目赤肿痛", "眼睑下垂", "眉棱骨痛", "面瘫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "EX_HN4_R", nameZh: "鱼腰(右)", pinyin: "YuYao",
               meridian: "经外奇穴", location: "瞳孔直上，眉毛中点处(右)",
               indications: ["目赤肿痛", "眼睑下垂", "眉棱骨痛", "面瘫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "TE23_L", nameZh: "丝竹空(左)", pinyin: "SiZhuKong",
               meridian: "手少阳三焦经", location: "眉梢外侧端凹陷中(左)",
               indications: ["头痛", "目赤肿痛", "眼睑跳动", "面瘫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "TE23_R", nameZh: "丝竹空(右)", pinyin: "SiZhuKong",
               meridian: "手少阳三焦经", location: "眉梢外侧端凹陷中(右)",
               indications: ["头痛", "目赤肿痛", "眼睑跳动", "面瘫"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "GB1_L", nameZh: "瞳子髎(左)", pinyin: "TongZiLiao",
               meridian: "足少阳胆经", location: "目外眦外侧0.5寸，眶骨外缘凹陷中(左)",
               indications: ["头痛", "目赤肿痛", "迎风流泪", "近视"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.4, y: 0.08)),
        .init(id: "GB1_R", nameZh: "瞳子髎(右)", pinyin: "TongZiLiao",
               meridian: "足少阳胆经", location: "目外眦外侧0.5寸，眶骨外缘凹陷中(右)",
               indications: ["头痛", "目赤肿痛", "迎风流泪", "近视"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.4, y: 0.08)),
        .init(id: "ST1_L", nameZh: "承泣(左)", pinyin: "ChengQi",
               meridian: "足阳明胃经", location: "瞳孔直下，眼球与眶下缘之间(左) - 使用眶下脸颊区域landmark",
               indications: ["目赤肿痛", "迎风流泪", "夜盲", "眼睑跳动"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.09)),
        .init(id: "ST1_R", nameZh: "承泣(右)", pinyin: "ChengQi",
               meridian: "足阳明胃经", location: "瞳孔直下，眼球与眶下缘之间(右) - 使用眶下脸颊区域landmark",
               indications: ["目赤肿痛", "迎风流泪", "夜盲", "眼睑跳动"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.09)),
        .init(id: "BL2_R", nameZh: "攒竹(右)", pinyin: "CuanZhu",
               meridian: "足太阳膀胱经", location: "眉头凹陷中，眶上切迹处(右)",
               indications: ["头痛", "目赤肿痛", "眼睑跳动"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.07)),
        .init(id: "GV24", nameZh: "神庭", pinyin: "ShenTing",
               meridian: "督脉", location: "前发际正中直上0.5寸",
               indications: ["头痛", "失眠", "眩晕"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.04)),
        .init(id: "GB20", nameZh: "風池", pinyin: "FengChi",
               meridian: "足少陽膽經", location: "後頸枕骨下胸鎖乳突肌與斜方肌之間凹陷",
               indications: ["頭痛", "頸僵", "目眩", "感冒"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.35, y: 0.14)),
        .init(id: "GV20", nameZh: "百會", pinyin: "BaiHui",
               meridian: "督脈", location: "頭頂正中線兩耳尖連線中點",
               indications: ["提神", "頭痛", "安神", "眩暈"], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.02)),
        .init(id: "SI11", nameZh: "天宗", pinyin: "TianZong",
               meridian: "手太陽小腸經", location: "肩胛骨岡下窩中央凹陷",
               indications: ["肩胛痛", "上肢不遂"], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.32, y: 0.27)),
    ]
}
}
