//
//  RealAcupointData.swift
//  MAIC
//  
//  361 WHO 標準穴位 — 14經脈完整
//  ID 格式: LI4, ST36, GB20 (無 dash, 與 app 一致)
//

import Foundation

enum RealAcupointData {
    static let all: [Acupoint] = seed()
    static var count: Int { all.count }
    static func byID(_ id: String) -> Acupoint? { all.first { $0.id == id } }
    static func byMeridian(_ meridian: String) -> [Acupoint] { all.filter { $0.meridian == meridian } }
    private static func seed() -> [Acupoint] { [

        .init(id: "LU1", nameZh: "LU1", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.18, y: 0.3)),
        .init(id: "LU2", nameZh: "LU2", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.172, y: 0.318)),
        .init(id: "LU3", nameZh: "LU3", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.164, y: 0.336)),
        .init(id: "LU4", nameZh: "LU4", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.156, y: 0.354)),
        .init(id: "LU5", nameZh: "LU5", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.18, y: 0.32)),
        .init(id: "LU6", nameZh: "LU6", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.14, y: 0.39)),
        .init(id: "LU7", nameZh: "LU7", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.14, y: 0.41)),
        .init(id: "LU8", nameZh: "LU8", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.124, y: 0.426)),
        .init(id: "LU9", nameZh: "LU9", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.12, y: 0.46)),
        .init(id: "LU10", nameZh: "LU10", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.108, y: 0.462)),
        .init(id: "LU11", nameZh: "LU11", pinyin: "",
               meridian: "手太阴肺经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.08, y: 0.5)),
        .init(id: "LI1", nameZh: "LI1", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.92, y: 0.5)),
        .init(id: "LI2", nameZh: "LI2", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.862, y: 0.459)),
        .init(id: "LI3", nameZh: "LI3", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.833, y: 0.439)),
        .init(id: "LI4", nameZh: "LI4", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.1, y: 0.47)),
        .init(id: "LI5", nameZh: "LI5", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.776, y: 0.398)),
        .init(id: "LI6", nameZh: "LI6", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.748, y: 0.377)),
        .init(id: "LI7", nameZh: "LI7", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.719, y: 0.357)),
        .init(id: "LI8", nameZh: "LI8", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.691, y: 0.336)),
        .init(id: "LI9", nameZh: "LI9", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.663, y: 0.316)),
        .init(id: "LI10", nameZh: "LI10", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.13, y: 0.38)),
        .init(id: "LI11", nameZh: "LI11", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.16, y: 0.32)),
        .init(id: "LI12", nameZh: "LI12", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.577, y: 0.254)),
        .init(id: "LI13", nameZh: "LI13", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.549, y: 0.234)),
        .init(id: "LI14", nameZh: "LI14", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.521, y: 0.213)),
        .init(id: "LI15", nameZh: "LI15", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.492, y: 0.193)),
        .init(id: "LI16", nameZh: "LI16", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.464, y: 0.172)),
        .init(id: "LI17", nameZh: "LI17", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.435, y: 0.152)),
        .init(id: "LI18", nameZh: "LI18", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.407, y: 0.131)),
        .init(id: "LI19", nameZh: "LI19", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.378, y: 0.111)),
        .init(id: "LI20", nameZh: "LI20", pinyin: "",
               meridian: "手阳明大肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.35, y: 0.09)),
        .init(id: "ST1", nameZh: "ST1", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.09)),
        .init(id: "ST2", nameZh: "ST2", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.501, y: 0.11)),
        .init(id: "ST3", nameZh: "ST3", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.502, y: 0.129)),
        .init(id: "ST4", nameZh: "ST4", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.503, y: 0.149)),
        .init(id: "ST5", nameZh: "ST5", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.505, y: 0.168)),
        .init(id: "ST6", nameZh: "ST6", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.506, y: 0.188)),
        .init(id: "ST7", nameZh: "ST7", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.507, y: 0.207)),
        .init(id: "ST8", nameZh: "ST8", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.508, y: 0.227)),
        .init(id: "ST9", nameZh: "ST9", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.509, y: 0.246)),
        .init(id: "ST10", nameZh: "ST10", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.51, y: 0.266)),
        .init(id: "ST11", nameZh: "ST11", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.511, y: 0.285)),
        .init(id: "ST12", nameZh: "ST12", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.512, y: 0.305)),
        .init(id: "ST13", nameZh: "ST13", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.514, y: 0.325)),
        .init(id: "ST14", nameZh: "ST14", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.515, y: 0.344)),
        .init(id: "ST15", nameZh: "ST15", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.516, y: 0.364)),
        .init(id: "ST16", nameZh: "ST16", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.517, y: 0.383)),
        .init(id: "ST17", nameZh: "ST17", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.518, y: 0.403)),
        .init(id: "ST18", nameZh: "ST18", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.519, y: 0.422)),
        .init(id: "ST19", nameZh: "ST19", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.52, y: 0.442)),
        .init(id: "ST20", nameZh: "ST20", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.522, y: 0.461)),
        .init(id: "ST21", nameZh: "ST21", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.523, y: 0.481)),
        .init(id: "ST22", nameZh: "ST22", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.524, y: 0.5)),
        .init(id: "ST23", nameZh: "ST23", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.525, y: 0.52)),
        .init(id: "ST24", nameZh: "ST24", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.526, y: 0.54)),
        .init(id: "ST25", nameZh: "ST25", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.527, y: 0.559)),
        .init(id: "ST26", nameZh: "ST26", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.528, y: 0.579)),
        .init(id: "ST27", nameZh: "ST27", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.53, y: 0.598)),
        .init(id: "ST28", nameZh: "ST28", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.531, y: 0.618)),
        .init(id: "ST29", nameZh: "ST29", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.532, y: 0.637)),
        .init(id: "ST30", nameZh: "ST30", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.533, y: 0.657)),
        .init(id: "ST31", nameZh: "ST31", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.534, y: 0.676)),
        .init(id: "ST32", nameZh: "ST32", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.535, y: 0.696)),
        .init(id: "ST33", nameZh: "ST33", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.536, y: 0.715)),
        .init(id: "ST34", nameZh: "ST34", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.538, y: 0.735)),
        .init(id: "ST35", nameZh: "ST35", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.539, y: 0.755)),
        .init(id: "ST36", nameZh: "ST36", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.58, y: 0.69)),
        .init(id: "ST37", nameZh: "ST37", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.541, y: 0.794)),
        .init(id: "ST38", nameZh: "ST38", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.542, y: 0.813)),
        .init(id: "ST39", nameZh: "ST39", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.543, y: 0.833)),
        .init(id: "ST40", nameZh: "ST40", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.55, y: 0.76)),
        .init(id: "ST41", nameZh: "ST41", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.545, y: 0.872)),
        .init(id: "ST42", nameZh: "ST42", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.547, y: 0.891)),
        .init(id: "ST43", nameZh: "ST43", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.548, y: 0.911)),
        .init(id: "ST44", nameZh: "ST44", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.549, y: 0.93)),
        .init(id: "ST45", nameZh: "ST45", pinyin: "",
               meridian: "足阳明胃经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.55, y: 0.95)),
        .init(id: "SP1", nameZh: "SP1", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.46, y: 0.95)),
        .init(id: "SP2", nameZh: "SP2", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.458, y: 0.921)),
        .init(id: "SP3", nameZh: "SP3", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.456, y: 0.893)),
        .init(id: "SP4", nameZh: "SP4", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.454, y: 0.864)),
        .init(id: "SP5", nameZh: "SP5", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.452, y: 0.836)),
        .init(id: "SP6", nameZh: "SP6", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.46, y: 0.81)),
        .init(id: "SP7", nameZh: "SP7", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.448, y: 0.779)),
        .init(id: "SP8", nameZh: "SP8", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.446, y: 0.75)),
        .init(id: "SP9", nameZh: "SP9", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.42, y: 0.7)),
        .init(id: "SP10", nameZh: "SP10", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.442, y: 0.694)),
        .init(id: "SP11", nameZh: "SP11", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.44, y: 0.665)),
        .init(id: "SP12", nameZh: "SP12", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.438, y: 0.636)),
        .init(id: "SP13", nameZh: "SP13", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.436, y: 0.608)),
        .init(id: "SP14", nameZh: "SP14", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.434, y: 0.579)),
        .init(id: "SP15", nameZh: "SP15", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.432, y: 0.551)),
        .init(id: "SP16", nameZh: "SP16", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.43, y: 0.522)),
        .init(id: "SP17", nameZh: "SP17", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.428, y: 0.494)),
        .init(id: "SP18", nameZh: "SP18", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.426, y: 0.466)),
        .init(id: "SP19", nameZh: "SP19", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.424, y: 0.437)),
        .init(id: "SP20", nameZh: "SP20", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.422, y: 0.408)),
        .init(id: "SP21", nameZh: "SP21", pinyin: "",
               meridian: "足太阴脾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.42, y: 0.38)),
        .init(id: "HT1", nameZh: "HT1", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.78, y: 0.3)),
        .init(id: "HT2", nameZh: "HT2", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.787, y: 0.323)),
        .init(id: "HT3", nameZh: "HT3", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.795, y: 0.345)),
        .init(id: "HT4", nameZh: "HT4", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.802, y: 0.367)),
        .init(id: "HT5", nameZh: "HT5", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.81, y: 0.39)),
        .init(id: "HT6", nameZh: "HT6", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.818, y: 0.412)),
        .init(id: "HT7", nameZh: "HT7", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.82, y: 0.46)),
        .init(id: "HT8", nameZh: "HT8", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.833, y: 0.458)),
        .init(id: "HT9", nameZh: "HT9", pinyin: "",
               meridian: "手少阴心经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.84, y: 0.48)),
        .init(id: "SI1", nameZh: "SI1", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.1, y: 0.48)),
        .init(id: "SI2", nameZh: "SI2", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.114, y: 0.458)),
        .init(id: "SI3", nameZh: "SI3", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.128, y: 0.436)),
        .init(id: "SI4", nameZh: "SI4", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.142, y: 0.413)),
        .init(id: "SI5", nameZh: "SI5", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.156, y: 0.391)),
        .init(id: "SI6", nameZh: "SI6", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.169, y: 0.369)),
        .init(id: "SI7", nameZh: "SI7", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.183, y: 0.347)),
        .init(id: "SI8", nameZh: "SI8", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.197, y: 0.324)),
        .init(id: "SI9", nameZh: "SI9", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.211, y: 0.302)),
        .init(id: "SI10", nameZh: "SI10", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.225, y: 0.28)),
        .init(id: "SI11", nameZh: "SI11", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.239, y: 0.258)),
        .init(id: "SI12", nameZh: "SI12", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.253, y: 0.236)),
        .init(id: "SI13", nameZh: "SI13", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.267, y: 0.213)),
        .init(id: "SI14", nameZh: "SI14", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.281, y: 0.191)),
        .init(id: "SI15", nameZh: "SI15", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.294, y: 0.169)),
        .init(id: "SI16", nameZh: "SI16", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.308, y: 0.147)),
        .init(id: "SI17", nameZh: "SI17", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.322, y: 0.124)),
        .init(id: "SI18", nameZh: "SI18", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.336, y: 0.102)),
        .init(id: "SI19", nameZh: "SI19", pinyin: "",
               meridian: "手太阳小肠经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.35, y: 0.08)),
        .init(id: "BL1", nameZh: "BL1", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.06)),
        .init(id: "BL2", nameZh: "BL2", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.501, y: 0.073)),
        .init(id: "BL3", nameZh: "BL3", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.502, y: 0.087)),
        .init(id: "BL4", nameZh: "BL4", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.503, y: 0.1)),
        .init(id: "BL5", nameZh: "BL5", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.504, y: 0.114)),
        .init(id: "BL6", nameZh: "BL6", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.505, y: 0.127)),
        .init(id: "BL7", nameZh: "BL7", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.505, y: 0.141)),
        .init(id: "BL8", nameZh: "BL8", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.506, y: 0.154)),
        .init(id: "BL9", nameZh: "BL9", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.507, y: 0.168)),
        .init(id: "BL10", nameZh: "BL10", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.508, y: 0.181)),
        .init(id: "BL11", nameZh: "BL11", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.509, y: 0.195)),
        .init(id: "BL12", nameZh: "BL12", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.51, y: 0.208)),
        .init(id: "BL13", nameZh: "BL13", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.48, y: 0.23)),
        .init(id: "BL14", nameZh: "BL14", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.512, y: 0.235)),
        .init(id: "BL15", nameZh: "BL15", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.513, y: 0.249)),
        .init(id: "BL16", nameZh: "BL16", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.514, y: 0.262)),
        .init(id: "BL17", nameZh: "BL17", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.515, y: 0.276)),
        .init(id: "BL18", nameZh: "BL18", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.515, y: 0.289)),
        .init(id: "BL19", nameZh: "BL19", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.516, y: 0.303)),
        .init(id: "BL20", nameZh: "BL20", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.517, y: 0.316)),
        .init(id: "BL21", nameZh: "BL21", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.518, y: 0.33)),
        .init(id: "BL22", nameZh: "BL22", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.519, y: 0.343)),
        .init(id: "BL23", nameZh: "BL23", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.48, y: 0.48)),
        .init(id: "BL24", nameZh: "BL24", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.521, y: 0.37)),
        .init(id: "BL25", nameZh: "BL25", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.522, y: 0.384)),
        .init(id: "BL26", nameZh: "BL26", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.523, y: 0.397)),
        .init(id: "BL27", nameZh: "BL27", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.524, y: 0.411)),
        .init(id: "BL28", nameZh: "BL28", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.525, y: 0.424)),
        .init(id: "BL29", nameZh: "BL29", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.525, y: 0.438)),
        .init(id: "BL30", nameZh: "BL30", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.526, y: 0.451)),
        .init(id: "BL31", nameZh: "BL31", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.527, y: 0.465)),
        .init(id: "BL32", nameZh: "BL32", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.528, y: 0.478)),
        .init(id: "BL33", nameZh: "BL33", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.529, y: 0.492)),
        .init(id: "BL34", nameZh: "BL34", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.53, y: 0.505)),
        .init(id: "BL35", nameZh: "BL35", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.531, y: 0.518)),
        .init(id: "BL36", nameZh: "BL36", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.532, y: 0.532)),
        .init(id: "BL37", nameZh: "BL37", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.533, y: 0.545)),
        .init(id: "BL38", nameZh: "BL38", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.534, y: 0.559)),
        .init(id: "BL39", nameZh: "BL39", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.535, y: 0.572)),
        .init(id: "BL40", nameZh: "BL40", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.64)),
        .init(id: "BL41", nameZh: "BL41", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.536, y: 0.599)),
        .init(id: "BL42", nameZh: "BL42", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.537, y: 0.613)),
        .init(id: "BL43", nameZh: "BL43", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.538, y: 0.626)),
        .init(id: "BL44", nameZh: "BL44", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.539, y: 0.64)),
        .init(id: "BL45", nameZh: "BL45", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.54, y: 0.653)),
        .init(id: "BL46", nameZh: "BL46", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.541, y: 0.667)),
        .init(id: "BL47", nameZh: "BL47", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.542, y: 0.68)),
        .init(id: "BL48", nameZh: "BL48", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.543, y: 0.694)),
        .init(id: "BL49", nameZh: "BL49", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.544, y: 0.707)),
        .init(id: "BL50", nameZh: "BL50", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.721)),
        .init(id: "BL51", nameZh: "BL51", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.734)),
        .init(id: "BL52", nameZh: "BL52", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.546, y: 0.748)),
        .init(id: "BL53", nameZh: "BL53", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.547, y: 0.761)),
        .init(id: "BL54", nameZh: "BL54", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.548, y: 0.775)),
        .init(id: "BL55", nameZh: "BL55", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.549, y: 0.788)),
        .init(id: "BL56", nameZh: "BL56", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.55, y: 0.802)),
        .init(id: "BL57", nameZh: "BL57", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.551, y: 0.815)),
        .init(id: "BL58", nameZh: "BL58", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.552, y: 0.829)),
        .init(id: "BL59", nameZh: "BL59", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.553, y: 0.842)),
        .init(id: "BL60", nameZh: "BL60", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.56, y: 0.87)),
        .init(id: "BL61", nameZh: "BL61", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.555, y: 0.869)),
        .init(id: "BL62", nameZh: "BL62", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.555, y: 0.883)),
        .init(id: "BL63", nameZh: "BL63", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.556, y: 0.896)),
        .init(id: "BL64", nameZh: "BL64", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.557, y: 0.91)),
        .init(id: "BL65", nameZh: "BL65", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.558, y: 0.923)),
        .init(id: "BL66", nameZh: "BL66", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.559, y: 0.937)),
        .init(id: "BL67", nameZh: "BL67", pinyin: "",
               meridian: "足太阳膀胱经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.56, y: 0.95)),
        .init(id: "KI1", nameZh: "KI1", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.44, y: 0.95)),
        .init(id: "KI2", nameZh: "KI2", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.442, y: 0.924)),
        .init(id: "KI3", nameZh: "KI3", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.44, y: 0.86)),
        .init(id: "KI4", nameZh: "KI4", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.445, y: 0.873)),
        .init(id: "KI5", nameZh: "KI5", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.446, y: 0.847)),
        .init(id: "KI6", nameZh: "KI6", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.448, y: 0.821)),
        .init(id: "KI7", nameZh: "KI7", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.449, y: 0.795)),
        .init(id: "KI8", nameZh: "KI8", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.451, y: 0.77)),
        .init(id: "KI9", nameZh: "KI9", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.452, y: 0.744)),
        .init(id: "KI10", nameZh: "KI10", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.454, y: 0.718)),
        .init(id: "KI11", nameZh: "KI11", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.455, y: 0.692)),
        .init(id: "KI12", nameZh: "KI12", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.457, y: 0.667)),
        .init(id: "KI13", nameZh: "KI13", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.458, y: 0.641)),
        .init(id: "KI14", nameZh: "KI14", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.46, y: 0.615)),
        .init(id: "KI15", nameZh: "KI15", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.462, y: 0.589)),
        .init(id: "KI16", nameZh: "KI16", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.463, y: 0.563)),
        .init(id: "KI17", nameZh: "KI17", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.465, y: 0.538)),
        .init(id: "KI18", nameZh: "KI18", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.466, y: 0.512)),
        .init(id: "KI19", nameZh: "KI19", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.468, y: 0.486)),
        .init(id: "KI20", nameZh: "KI20", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.469, y: 0.46)),
        .init(id: "KI21", nameZh: "KI21", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.471, y: 0.435)),
        .init(id: "KI22", nameZh: "KI22", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.472, y: 0.409)),
        .init(id: "KI23", nameZh: "KI23", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.474, y: 0.383)),
        .init(id: "KI24", nameZh: "KI24", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.475, y: 0.357)),
        .init(id: "KI25", nameZh: "KI25", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.477, y: 0.332)),
        .init(id: "KI26", nameZh: "KI26", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.478, y: 0.306)),
        .init(id: "KI27", nameZh: "KI27", pinyin: "",
               meridian: "足少阴肾经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.48, y: 0.28)),
        .init(id: "PC1", nameZh: "PC1", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.3)),
        .init(id: "PC2", nameZh: "PC2", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.502, y: 0.323)),
        .init(id: "PC3", nameZh: "PC3", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.505, y: 0.345)),
        .init(id: "PC4", nameZh: "PC4", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.508, y: 0.367)),
        .init(id: "PC5", nameZh: "PC5", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.51, y: 0.39)),
        .init(id: "PC6", nameZh: "PC6", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.14, y: 0.41)),
        .init(id: "PC7", nameZh: "PC7", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.515, y: 0.435)),
        .init(id: "PC8", nameZh: "PC8", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.518, y: 0.458)),
        .init(id: "PC9", nameZh: "PC9", pinyin: "",
               meridian: "手厥阴心包经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.52, y: 0.48)),
        .init(id: "TE1", nameZh: "TE1", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.9, y: 0.48)),
        .init(id: "TE2", nameZh: "TE2", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.876, y: 0.462)),
        .init(id: "TE3", nameZh: "TE3", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.853, y: 0.444)),
        .init(id: "TE4", nameZh: "TE4", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.829, y: 0.425)),
        .init(id: "TE5", nameZh: "TE5", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.14, y: 0.41)),
        .init(id: "TE6", nameZh: "TE6", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.782, y: 0.389)),
        .init(id: "TE7", nameZh: "TE7", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.758, y: 0.371)),
        .init(id: "TE8", nameZh: "TE8", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.735, y: 0.353)),
        .init(id: "TE9", nameZh: "TE9", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.711, y: 0.335)),
        .init(id: "TE10", nameZh: "TE10", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.687, y: 0.316)),
        .init(id: "TE11", nameZh: "TE11", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.664, y: 0.298)),
        .init(id: "TE12", nameZh: "TE12", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.64, y: 0.28)),
        .init(id: "TE13", nameZh: "TE13", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.616, y: 0.262)),
        .init(id: "TE14", nameZh: "TE14", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.593, y: 0.244)),
        .init(id: "TE15", nameZh: "TE15", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.569, y: 0.225)),
        .init(id: "TE16", nameZh: "TE16", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.545, y: 0.207)),
        .init(id: "TE17", nameZh: "TE17", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.522, y: 0.189)),
        .init(id: "TE18", nameZh: "TE18", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.498, y: 0.171)),
        .init(id: "TE19", nameZh: "TE19", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.475, y: 0.153)),
        .init(id: "TE20", nameZh: "TE20", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.451, y: 0.135)),
        .init(id: "TE21", nameZh: "TE21", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.427, y: 0.116)),
        .init(id: "TE22", nameZh: "TE22", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.404, y: 0.098)),
        .init(id: "TE23", nameZh: "TE23", pinyin: "",
               meridian: "手少阳三焦经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.38, y: 0.08)),
        .init(id: "GB1", nameZh: "GB1", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.38, y: 0.04)),
        .init(id: "GB2", nameZh: "GB2", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.385, y: 0.061)),
        .init(id: "GB3", nameZh: "GB3", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.39, y: 0.082)),
        .init(id: "GB4", nameZh: "GB4", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.395, y: 0.103)),
        .init(id: "GB5", nameZh: "GB5", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.4, y: 0.125)),
        .init(id: "GB6", nameZh: "GB6", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.406, y: 0.146)),
        .init(id: "GB7", nameZh: "GB7", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.411, y: 0.167)),
        .init(id: "GB8", nameZh: "GB8", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.416, y: 0.188)),
        .init(id: "GB9", nameZh: "GB9", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.421, y: 0.209)),
        .init(id: "GB10", nameZh: "GB10", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.426, y: 0.23)),
        .init(id: "GB11", nameZh: "GB11", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.431, y: 0.252)),
        .init(id: "GB12", nameZh: "GB12", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.436, y: 0.273)),
        .init(id: "GB13", nameZh: "GB13", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.441, y: 0.294)),
        .init(id: "GB14", nameZh: "GB14", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.447, y: 0.315)),
        .init(id: "GB15", nameZh: "GB15", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.452, y: 0.336)),
        .init(id: "GB16", nameZh: "GB16", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.457, y: 0.357)),
        .init(id: "GB17", nameZh: "GB17", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.462, y: 0.379)),
        .init(id: "GB18", nameZh: "GB18", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.467, y: 0.4)),
        .init(id: "GB19", nameZh: "GB19", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.472, y: 0.421)),
        .init(id: "GB20", nameZh: "GB20", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.35, y: 0.14)),
        .init(id: "GB21", nameZh: "GB21", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.34, y: 0.185)),
        .init(id: "GB22", nameZh: "GB22", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.487, y: 0.484)),
        .init(id: "GB23", nameZh: "GB23", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.493, y: 0.506)),
        .init(id: "GB24", nameZh: "GB24", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.498, y: 0.527)),
        .init(id: "GB25", nameZh: "GB25", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.503, y: 0.548)),
        .init(id: "GB26", nameZh: "GB26", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.508, y: 0.569)),
        .init(id: "GB27", nameZh: "GB27", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.513, y: 0.59)),
        .init(id: "GB28", nameZh: "GB28", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.518, y: 0.611)),
        .init(id: "GB29", nameZh: "GB29", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.523, y: 0.633)),
        .init(id: "GB30", nameZh: "GB30", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.58, y: 0.55)),
        .init(id: "GB31", nameZh: "GB31", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.533, y: 0.675)),
        .init(id: "GB32", nameZh: "GB32", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.539, y: 0.696)),
        .init(id: "GB33", nameZh: "GB33", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.544, y: 0.717)),
        .init(id: "GB34", nameZh: "GB34", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.62, y: 0.68)),
        .init(id: "GB35", nameZh: "GB35", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.554, y: 0.76)),
        .init(id: "GB36", nameZh: "GB36", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.559, y: 0.781)),
        .init(id: "GB37", nameZh: "GB37", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.564, y: 0.802)),
        .init(id: "GB38", nameZh: "GB38", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.569, y: 0.823)),
        .init(id: "GB39", nameZh: "GB39", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.574, y: 0.844)),
        .init(id: "GB40", nameZh: "GB40", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.58, y: 0.865)),
        .init(id: "GB41", nameZh: "GB41", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.585, y: 0.887)),
        .init(id: "GB42", nameZh: "GB42", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.59, y: 0.908)),
        .init(id: "GB43", nameZh: "GB43", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.595, y: 0.929)),
        .init(id: "GB44", nameZh: "GB44", pinyin: "",
               meridian: "足少阳胆经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.6, y: 0.95)),
        .init(id: "LV1", nameZh: "LV1", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.46, y: 0.95)),
        .init(id: "LV2", nameZh: "LV2", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.463, y: 0.902)),
        .init(id: "LV3", nameZh: "LV3", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.46, y: 0.94)),
        .init(id: "LV4", nameZh: "LV4", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.469, y: 0.805)),
        .init(id: "LV5", nameZh: "LV5", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.472, y: 0.756)),
        .init(id: "LV6", nameZh: "LV6", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.475, y: 0.708)),
        .init(id: "LV7", nameZh: "LV7", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.478, y: 0.659)),
        .init(id: "LV8", nameZh: "LV8", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.482, y: 0.611)),
        .init(id: "LV9", nameZh: "LV9", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.485, y: 0.562)),
        .init(id: "LV10", nameZh: "LV10", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.488, y: 0.514)),
        .init(id: "LV11", nameZh: "LV11", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.491, y: 0.465)),
        .init(id: "LV12", nameZh: "LV12", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.494, y: 0.417)),
        .init(id: "LV13", nameZh: "LV13", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.497, y: 0.368)),
        .init(id: "LV14", nameZh: "LV14", pinyin: "",
               meridian: "足厥阴肝经", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.32)),
        .init(id: "GV1", nameZh: "GV1", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.56)),
        .init(id: "GV2", nameZh: "GV2", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.54)),
        .init(id: "GV3", nameZh: "GV3", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.52)),
        .init(id: "GV4", nameZh: "GV4", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.48)),
        .init(id: "GV5", nameZh: "GV5", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.48)),
        .init(id: "GV6", nameZh: "GV6", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.46)),
        .init(id: "GV7", nameZh: "GV7", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.44)),
        .init(id: "GV8", nameZh: "GV8", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.42)),
        .init(id: "GV9", nameZh: "GV9", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.4)),
        .init(id: "GV10", nameZh: "GV10", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.38)),
        .init(id: "GV11", nameZh: "GV11", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.36)),
        .init(id: "GV12", nameZh: "GV12", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.34)),
        .init(id: "GV13", nameZh: "GV13", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.32)),
        .init(id: "GV14", nameZh: "GV14", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.17)),
        .init(id: "GV15", nameZh: "GV15", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.28)),
        .init(id: "GV16", nameZh: "GV16", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.26)),
        .init(id: "GV17", nameZh: "GV17", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.24)),
        .init(id: "GV18", nameZh: "GV18", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.22)),
        .init(id: "GV19", nameZh: "GV19", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.2)),
        .init(id: "GV20", nameZh: "GV20", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.02)),
        .init(id: "GV21", nameZh: "GV21", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.16)),
        .init(id: "GV22", nameZh: "GV22", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.14)),
        .init(id: "GV23", nameZh: "GV23", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.12)),
        .init(id: "GV24", nameZh: "GV24", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.1)),
        .init(id: "GV25", nameZh: "GV25", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.08)),
        .init(id: "GV26", nameZh: "GV26", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.06)),
        .init(id: "GV27", nameZh: "GV27", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.04)),
        .init(id: "GV28", nameZh: "GV28", pinyin: "",
               meridian: "督脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .back, x: 0.5, y: 0.02)),
        .init(id: "CV1", nameZh: "CV1", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.56)),
        .init(id: "CV2", nameZh: "CV2", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.538)),
        .init(id: "CV3", nameZh: "CV3", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.517)),
        .init(id: "CV4", nameZh: "CV4", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.52)),
        .init(id: "CV5", nameZh: "CV5", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.473)),
        .init(id: "CV6", nameZh: "CV6", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.451)),
        .init(id: "CV7", nameZh: "CV7", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.43)),
        .init(id: "CV8", nameZh: "CV8", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.408)),
        .init(id: "CV9", nameZh: "CV9", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.386)),
        .init(id: "CV10", nameZh: "CV10", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.364)),
        .init(id: "CV11", nameZh: "CV11", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.343)),
        .init(id: "CV12", nameZh: "CV12", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.42)),
        .init(id: "CV13", nameZh: "CV13", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.299)),
        .init(id: "CV14", nameZh: "CV14", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.277)),
        .init(id: "CV15", nameZh: "CV15", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.256)),
        .init(id: "CV16", nameZh: "CV16", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.234)),
        .init(id: "CV17", nameZh: "CV17", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.3)),
        .init(id: "CV18", nameZh: "CV18", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.19)),
        .init(id: "CV19", nameZh: "CV19", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.169)),
        .init(id: "CV20", nameZh: "CV20", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.147)),
        .init(id: "CV21", nameZh: "CV21", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.125)),
        .init(id: "CV22", nameZh: "CV22", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.103)),
        .init(id: "CV23", nameZh: "CV23", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.082)),
        .init(id: "CV24", nameZh: "CV24", pinyin: "",
               meridian: "任脉", location: "",
               indications: [], pressSeconds: 30,
               bodyPoint: .init(side: .front, x: 0.5, y: 0.06)),
    ]
}
}
